---
title: "Cross-cultural heterogeneity"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparations

## Packages

```{r}

library(devtools)
library(lme4)
library(lmerTest)
library(r2mlm)
library(rio)
library(dplyr)
library(vjihelpers)
library(tibble)
library(ggplot2)
library(ggflags)
library(MetBrewer)
library(finalfit)
library(performance)
```

## Functions

```{r}

source("../custom_functions.R")
```

## Data

```{r}
fdat<-import("../../data/processed/fdat.xlsx")
```

## Variables

```{r}

value.vars<-
  c("con","tra","ben","uni","sdi",
        "sti","hed","ach","pow","sec")

value.vars.c<-paste0(value.vars,".c")

DV.vars<-names(fdat)[which(names(fdat)=="lrgen.z"):
                       which(names(fdat)=="corrupt_salience.z")]


DV.names<-
  c("Left-Right General",
    "Left-Right Economic",
    "GAL-TAN",
    "Public services vs. reducing taxes",
    "Deregulation of markets",
    "Redistribution of wealth",
    "State intervention in the economy",
    "Civil liberties vs. law and order",
    "Social lifestyle policies",
    "Religious principles",
    "Immigration policy",
    "Multiculturalism vs. assimilation",
    "Urban vs. rural interests",
    "Environmental protection vs. economic growth",
    "Decentralization to regions/localities",
    "International troop deployment",
    "Rights of ethnic minorities",
    "Cosmopolitanism vs. nationalism",
    "Left-Right Economic salience",
    "GAL-TAN salience",
    "Anti-elite",
    "Reducing corruption")


Value.names<-
  c("Conformity",
    "Tradition",
    "Benevolence",
    "Universalism",
    "Self-direction",
    "Stimulation",
    "Hedonism",
    "Achievement",
    "Power",
    "Security")


```

# Analysis call

```{r}
length(DV.vars)
t1<-Sys.time()

pdf("../../results/figures/Country_specific_figures.pdf",
    onefile=T,width=11.7,height=8.3)

for (k in 1:length(DV.vars)){
  Heterogeneity_plot_pipe(DV=DV.vars[k],
                  IV=value.vars,
                  data=fdat,
                  IV.c=value.vars.c,
                  directory="../../results/main")
  
}
t2<-Sys.time()

dev.off()
t2-t1
```

# Session info

```{r}
sinf<-sessionInfo()
print(sinf,locale=F)
```